### ISSUE TITLE
Сумма чисел из файлов

### ISSUE THREAD

**Issue by mariyadavydova** [JetBrains/imperative-nodejs#1]
Даны 3 файла, в каждом из которых по одному числу (для простоты, от -10^6 до 10^6). Требуется прочитать все файлы и вывести сумму чисел.

Решить с использованием:
1. Callbacks (CoffeeScript/ClojureScript)
2. Promises (CoffeeScript/ClojureScript)
3. Core.Async (ClojureScript)

**Comment by matklad** [comment]
https://github.com/JetBrains/imperative-nodejs/tree/master/playground/src/playground/task1
