### ISSUE TITLE
Profiling tool

### ISSUE THREAD

**Issue by penemue** [JetBrains/imperative-nodejs#15]
Can we use a profiling tool to analyze benchmarks' execution? CPU and memory profiling would be nice.

**Comment by mariyadavydova** [comment]
I've found the following options:
http://blog.nodejs.org/2012/04/25/profiling-node-js/
http://blog.jetbrains.com/webstorm/2015/05/node-js-profiling-in-webstorm-part-1-cpu-profiling/

**Comment by matklad** [comment]
WebStorm profiler is  nice, perf + flamegraph is really nice, though a bit hard to set up
https://gist.github.com/trevnorris/9616784
