### ISSUE TITLE
Путь по файлам

### ISSUE THREAD

**Issue by mariyadavydova** [JetBrains/imperative-nodejs#2]
Даны N файлов с названиями от 1 до N, в каждом из которых записано уникальное число от 1 до N, а в одном из файлов --- 0. Так же дано число K от 1 до N. Число в файле гарантировано не равно его названию. Необходимо имплементировать такой алгоритм перехода по файлам:
0) I = K
1) Read J from file I
2) If J > 0 then I = J; goto 1; else exit
Вывести полученный таким образом путь.
(Файлов может быть много, читать все разом запрещено).

Решить с использованием:
1. Callbacks (CoffeeScript/ClojureScript)
2. Promises (CoffeeScript/ClojureScript)
3. Core.Async (ClojureScript)

**Comment by matklad** [comment]
https://github.com/JetBrains/imperative-nodejs/tree/master/playground/src/playground/task2
