### ISSUE TITLE
Abstract ObjectCache data structure similar to that in Xodus

### ISSUE THREAD

**Issue by penemue** [JetBrains/imperative-nodejs#22]
Generally, it's a hash table with limited size. An item of the cache is a key/value pair.

Features:
- Consists of two queues (LinkedHashMaps in Java), probation and protected. Each queue has its own maximum size. Ratio of their sizes can be a parameter of the cache, by default 1:1 is ok. Variant: sum of the queues' sizes must not exceed the size of the cache.
- Each new item is put into the head of probation queue. Any re-used item is shifted into the head of protected queue. 
- Items pulled out of probation queue are removed from the cache. Items pulled out of protected queue are shifted into the head of probation queue.
- The cache should accept a function that is called for any manually removed or pulled out item.

Methods:
- `get(key): object`
- `put(key, object): object`
- `remove(key): object`
- `contains(key): object`

Method `get()` updates the queues, whereas `contains()` doesn't. Also it would be nice to have an ability to enumerate all items or to call a function for all items.

**Comment by matklad** [comment]
https://github.com/JetBrains/imperative-nodejs/blob/master/lib/object_cache.js
