### ISSUE TITLE
TODO application

### ISSUE THREAD

**Issue by mariyadavydova** [JetBrains/imperative-nodejs#24]
Implement a TODO application on NodeJS using ES6 features.
Support console API:
* `create-user <login>` - create a user with a specified not-empty login (an empty login should be treated as an error; error if a user exists already).
* `remove-user <login>` - remove the specified user (error if a user is not found) and all his todos.
* `add-todo <login> <text>` - add a todo item with a specified text to a given user (error if a user is not found); when added an item should get an id (unique for a given user among all his todos, both active and checked, e.g. number).
* `get-todos <login>` - get all the active (unchecked) todos of the given user (error if a user is not found); return texts and ids.
* `remove-todo <login> <id>` - remove (i.e. mark as checked) a todo item with the given id of the given user (error if a user is not found; error if an item is not found or is checked already).

**Comment by mariyadavydova** [comment]
Optionally: implement a web-server with a corresponding REST API and very simple web UI for it.

**Comment by matklad** [comment]
* `remove-todo <login> <id>` -- deletes a todo item from the list completely.
* `[un]check-todo <login> <id>` -- marks a todo as [un]done.

**Comment by mariyadavydova** [comment]
I've thought about check-uncheck, but if want to support it, you'll have to hold some item state (checked/unchecked flag) and support two getters:
* get-todos <login> - get all active (unchecked) todos of the given user (error if a user is not found); return texts and ids.
* get-all-todos <login> - get all todos (both checked and unchecked).
So, each todo item can be in 3 states: created&unchecked; created&checked; removed.

**Comment by penemue** [comment]
I suggest also:
* `search <login> <text>` - search for active todos containing `<text>`.
* `search-all <login> <text>` - search for all existing todos containing `<text>`.

**Comment by mariyadavydova** [comment]
Good idea!

**Comment by matklad** [comment]
Both cli and web versions are ready.
