### ISSUE TITLE
Restructure project

### ISSUE THREAD

**Issue by mariyadavydova** [JetBrains/imperative-nodejs#29]
`src` and `test` directories should contain only the code relevant to Xodus.
`playground` should contain the code irrelevant to Xodus (including todo app and its gui).
Feel free to make as many subdirs and subprojects in playground as you need.

**Comment by mariyadavydova** [comment]
Please remove the `src/todo` and `node-gui` also.

**Comment by matklad** [comment]
WebStorm copies directories instead of moving them with drag'n'drop =(
