### ISSUE TITLE
Асинхронное чтение

### ISSUE THREAD

**Issue by mariyadavydova** [JetBrains/imperative-nodejs#3]
Иммитировать длительное асинхронное чтение: в программу поступает несколько запросов на чтение разных файлов, запросы приходят через нефиксированные промежутки времени, чтение выполняется асинхронно неизвестное время (например, поток искусственно спит), все результаты вывести по мере получения. Убедиться, что каждый ответ соответствует именно своему запросу, а не на первому выполненному.

Решить с использованием:
1. Callbacks (CoffeeScript/ClojureScript)
2. Promises (CoffeeScript/ClojureScript)
3. Core.Async (ClojureScript)

**Comment by matklad** [comment]
https://github.com/JetBrains/imperative-nodejs/tree/master/playground/src/playground/task3
