### ISSUE TITLE
Запись данных с проверкой успешности

### ISSUE THREAD

**Issue by mariyadavydova** [JetBrains/imperative-nodejs#4]
Чтение данных - одна сторона работы с базой данных. Необходимо так же асинхронно писать данные, обязательно получая информацию о том, записаны ли данные на самом деле. Предлагается попробовать записать данные в несколько файлов и завершиться после того, как будет понятно, что запись прошла успешно или неуспешно.

Решить с использованием:
1. Callbacks (CoffeeScript/ClojureScript)
2. Promises (CoffeeScript/ClojureScript)
3. Core.Async (ClojureScript)

**Comment by matklad** [comment]
https://github.com/JetBrains/imperative-nodejs/tree/master/playground/src/playground/task4
